version: '3.8'
services:
  reservations-service:
    build: ./reservations-service
    ports:
      - "3001:3001"
    environment:
      - DYNAMODB_ENDPOINT=http://localstack:4566
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
  payments-service:
    build: ./payments-service
    ports:
      - "3002:3002"
    environment:
      - DYNAMODB_ENDPOINT=http://localstack:4566
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
  notifications-service:
    build: ./notifications-service
    ports:
      - "3003:3003"
    environment:
      - DYNAMODB_ENDPOINT=http://localstack:4566
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=dynamodb
      - DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    volumes:
      - ./localstack/init-localstack.sh:/docker-entrypoint-initaws.d/init-localstack.sh
    command: >
      sh -c "
        chmod +x /docker-entrypoint-initaws.d/init-localstack.sh &&
        /docker-entrypoint-initaws.d/init-localstack.sh &&
        start-localstack
      "