version: '3.8'
services:
  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=dynamodb
      - START_WEB=0
      - DEFAULT_REGION=us-east-1
    volumes:
      - ./data:/tmp/localstack/data:rw

  hotel-service:
    build: ./hotel-service
    environment:
      - LOCALSTACK_HOSTNAME=localstack
    depends_on:
      - localstack
  
  paymant-service:
    build: ./payment-service
    environment:
      - LOCALSTACK_HOSTNAME=localstack
    depends_on:
      - localstack

  notification-service:
    build: ./notification-service
    environment:
      - LOCALSTACK_HOSTNAME=localstack
    depends_on:
      - localstack